tracker/urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'tracker.views.start_tracker'),

    url(r'^(\d+)/$', 'tracker.views.tracker', name="tracker-track"),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

tracker/models.py
import datetime

from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey(Project, related_name="tasks")
    name = models.CharField(max_length=50)
    finished = models.BooleanField()

    def __unicode__(self):
        return u'%s: %s' % (self.project.name, self.name)

    def cumulative_time(self):
        time = 0
        for chunk in self.chunks.filter(end__isnull=False):
            time += chunk.duration()
        return time


class Chunk(models.Model):
    task = models.ForeignKey(Task, related_name="chunks")
    start = models.DateTimeField()
    end = models.DateTimeField(null=True, blank=True)
    notes = models.TextField()

    def __unicode__(self):
        return u'%s: %s' % (self.task.name, self.duration())
    
    def finish(self):
        self.end = datetime.datetime.now()
        self.save()

    def ordinal(self):
        return self.task.chunks.filter(start__lte=self.start).count()

    def duration(self):
        return self.end and (self.end - self.start).seconds / 60

tracker/forms.py
from django import forms

import models


class ProjectTaskForm(forms.Form):
    project = forms.ModelChoiceField(
        queryset=models.Project.objects.order_by('name'))
    task = forms.ModelChoiceField(
        queryset=models.Task.objects.filter(finished=False).
                     order_by('project__name', 'name'),
        required=False)
    new_task = forms.CharField(required=False)

    def clean(self):
        project = self.cleaned_data.get('project')
        task = self.cleaned_data.get('task')
        if project and task and task.project != project:
            raise forms.ValidationError("Task is not valid for project")
        return self.cleaned_data


class ChunkNotesForm(forms.Form):
    notes = forms.CharField(widget=forms.Textarea, required=False)

tracker/views.py
import datetime
import time

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response


# local app imports
import forms
import models


def start_tracker(request):
    misc = models.Task.objects.get(name='misc')
    chunk = models.Chunk.objects.create(task=misc,
                                              start=datetime.datetime.now())
    return HttpResponseRedirect(reverse('tracker-track',
                                        args=(chunk.pk,)))


def tracker(request, chunk_id):
    chunk = get_object_or_404(models.Chunk, pk=chunk_id)
    if request.method == 'POST':
        task_form = forms.ProjectTaskForm(request.POST)
        notes_form = forms.ChunkNotesForm(request.POST)
        if request.POST.has_key('save') and notes_form.is_valid():
            chunk.notes = notes_form.cleaned_data['notes']
            chunk.save()
            return HttpResponseRedirect(reverse('tracker-track',
                                                args=(chunk.pk,)))
        elif request.POST.has_key('new') and notes_form.is_valid():
            chunk.notes = notes_form.cleaned_data['notes']
            chunk.finish()
            new_chunk = models.Chunk.objects.create(
                start=datetime.datetime.now(),
                task=chunk.task)
            return HttpResponseRedirect(reverse('tracker-track',
                                                args=(new_chunk.pk,)))
        elif request.POST.has_key('stop') and notes_form.is_valid():
            chunk.notes = notes_form.cleaned_data['notes']
            chunk.finish()
            misc_task = models.Task.objects.get(project__name='misc',
                                                name='misc')
            new_chunk = models.Chunk.objects.create(
                start=datetime.datetime.now(),
                task=misc_task)
            return HttpResponseRedirect(reverse('tracker-track',
                                                args=(new_chunk.pk,)))
        elif request.POST.has_key('finish') and notes_form.is_valid():
            chunk.notes = notes_form.cleaned_data['notes']
            chunk.finish()
            chunk.task.finished = True
            chunk.task.save()
            misc_task = models.Task.objects.get(project__name='misc',
                                                name='misc')
            new_chunk = models.Chunk.objects.create(
                start=datetime.datetime.now(),
                task=misc_task)
            return HttpResponseRedirect(reverse('tracker-track',
                                                args=(new_chunk.pk,)))
        elif (request.POST.has_key('switch') and 
              task_form.is_valid() and 
              notes_form.is_valid()):
            chunk.notes = notes_form.cleaned_data['notes']
            chunk.end = datetime.datetime.now()
            chunk.save()
            if task_form.cleaned_data['new_task']:
                new_task = models.Task.objects.create(
                    project=task_form.cleaned_data['project'],
                    name=task_form.cleaned_data['new_task'])
            elif task_form.cleaned_data['task']:
                new_task = task_form.cleaned_data['task']
            else:
                new_task = task_form.cleaned_data['project'].tasks.get(
                    name='misc')
            new_chunk = models.Chunk.objects.create(
                start=datetime.datetime.now(),
                task=new_task)
            return HttpResponseRedirect(reverse('tracker-track',
                                                args=(new_chunk.pk,)))
    else:
        task_form = forms.ProjectTaskForm()
        notes_form = forms.ChunkNotesForm(initial={'notes': chunk.notes})
    js_time = time.mktime(chunk.start.timetuple()) * 1000
    return render_to_response(
        'tracker/tracker.html',
        {'task_form': task_form,
         'chunk': chunk,
         'chunks': models.Chunk.objects.
             exclude(pk=chunk.pk).
             order_by('-start'),
         'js_time': js_time,
         'notes_form': notes_form})

tracker/templates/tracker/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Tracker</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="http://code.jquery.com/jquery-1.4.2.min.js"></script>
  </head>
  <body>
  {% block content %}
  {% endblock %}
  </body>
</html>

tracker/templates/tracker/tracker.html
{% extends "tracker/base.html" %}
{% block content %}
{% with chunk.task as task %}
    <h1>Tracker: {{ task.project.name }} &rarr; {{ task.name }} &rarr; chunk {{ chunk.ordinal }}</h1>
{% endwith %}
<table width="100%">
    <tr>
        <td valign="top">
            <form method="post" action=".">
                <!-- TODO refresh timesince dynamically -->
                <p>Task time: {{ chunk.task.cumulative_time }} minutes</p>
                <p>This chunk: <span id="chunk_time">{{ chunk.start|timesince }}</span> minutes</p>
                {{ notes_form.as_p }}
                <input type="submit" name="save" value="save chunk"> |
                <input type="submit" name="new" value="new chunk"> |
                <input type="submit" name="stop" value="stop task"> |
                <input type="submit" name="finish" value="finish task">
                {% if task_form.errors %}{{ task_form.errors }}{% endif %}
                <p>switch to: {% for field in task_form %}{% ifequal forloop.counter 2 %}<div id="task_picker">{% endifequal %}{{ field.label_tag }} {{ field }} {% endfor %}<input type="submit" name="switch" value="go"></div></p>
            </form>
        </td>
        <td valign="top" width="25%"x>
            {% for chunk in chunks %}
                <dl>
                    <dt>{{ chunk.task.project.name }} &rarr; {{ chunk.task.name }} &rarr; {{ chunk.ordinal }}: {{ chunk.duration }} minutes</dt>
                    <dl><pre>{{ chunk.notes }}</pre></dl>
                </dl>
            {% endfor %}
        </td>
    </tr>
</table>
<script>
$(function () {
    var chunk_time = $('#chunk_time');
    var start_time = new Date({{ js_time }});
    var one_minute = 60000  // milliseconds 
    var task_picker = $('#task_picker');
    var project_picker = $('#id_project');
    var current_task_picker = $('#id_task');

    // events
    project_picker.change(function () {
        var project = $(this).find('option:selected').text();
        if (!project) {
            task_picker.hide();
        } else {
            current_task_picker.find('option').each(function () {
                var option = $(this);
                if (option.text().split(':')[0] === project) {
                    option.show();
                } else {
                    option.hide();
                }
            });
            task_picker.show();
        }
    });    

    // utility functions
    var update_chunk_time = function () {
        var now = new Date;
        var elapsed = Math.round((now - start_time) / one_minute);
        chunk_time.text(elapsed);
    }

    var init = function () {
        task_picker.hide();
        update_chunk_time();
        setInterval(update_chunk_time, one_minute);
       
    }();
})
</script>
{% endblock %}